services:
  jupyter-dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jupyter-dev
    ports:
      - "8888:8888"
    volumes:
      - ./data:/app/data
      - ./.kaggle:/app/.kaggle:ro
    command: >
      jupyter notebook
      --port=8888
      --ip=0.0.0.0
      --no-browser
      --allow-root
