FROM python:3.12-slim
RUN apt-get update && \
    apt-get install -y gcc && \
    rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY requirements.txt .
RUN pip install --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt
EXPOSE 1811
CMD ["jupyter", "notebook", "--port=1811", "--ip=0.0.0.0", "--no-browser", \
     "--allow-root"]
