FROM python:3.12-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt
EXPOSE 1811
CMD ["jupyter", "notebook", "--port=1811", "--ip=0.0.0.0", "--no-browser", \
     "--allow-root"]
