services:
  movie-recommendation-system:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - data:/app/data
      - cache:/app/cache
    env_file:
      - .env
volumes:
  data:
  cache:
