services:
  jupyter-dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jupyter-dev
    ports:
      - "1811:1811"
    volumes:
      - ./data:/app/data
    command: >
      jupyter notebook
      --port=1811
      --ip=0.0.0.0
      --no-browser
      --allow-root
